"""visual_review.py — automate the visual QA pass on an AOSIS deck.

Two modes:

  prepare:   python visual_review.py path/to/deck.pptx /tmp/review/
             Converts the deck to per-slide JPEGs, writes a review prompt and
             an empty report template ready to be filled by a vision-capable
             Claude (or a human reviewer).

  summarize: python visual_review.py --summarize /tmp/review/review_report.json
             Reads a filled report and prints a defects summary grouped by
             slide and severity.

Requires `soffice` (LibreOffice) and `pdftoppm` (poppler-utils) on $PATH for
the prepare step. The summarize step has no system dependency.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from pptx import Presentation


REQUIRED_TOOLS = ("soffice", "pdftoppm")

SEVERITIES = ("critical", "important", "minor")

CATEGORIES = (
    "overflow",
    "alignment",
    "legibility",
    "palette",
    "typography",
    "title",
    "empty",
)


# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------
def _check_system_dependencies() -> None:
    """Fail fast with an actionable message if soffice/pdftoppm are missing."""
    missing = [t for t in REQUIRED_TOOLS if shutil.which(t) is None]
    if not missing:
        return
    hints = []
    if "soffice" in missing:
        hints.append(
            "  - 'soffice' not found. Install LibreOffice:\n"
            "      Ubuntu/Debian: sudo apt install libreoffice\n"
            "      macOS:         brew install --cask libreoffice"
        )
    if "pdftoppm" in missing:
        hints.append(
            "  - 'pdftoppm' not found. Install poppler-utils:\n"
            "      Ubuntu/Debian: sudo apt install poppler-utils\n"
            "      macOS:         brew install poppler"
        )
    raise SystemExit("Error: required tools missing.\n" + "\n".join(hints))


# ---------------------------------------------------------------------------
# Conversion pipeline
# ---------------------------------------------------------------------------
def _pptx_to_pdf(pptx_path: Path, work_dir: Path) -> Path:
    """Run soffice headless to produce a PDF. Returns the PDF path."""
    cmd = [
        "soffice",
        "--headless",
        "--convert-to", "pdf",
        "--outdir", str(work_dir),
        str(pptx_path),
    ]
    subprocess.run(cmd, check=True, capture_output=True, text=True)
    pdf_path = work_dir / (pptx_path.stem + ".pdf")
    if not pdf_path.exists():
        raise RuntimeError(f"soffice did not produce a PDF at {pdf_path}")
    return pdf_path


def _pdf_to_jpegs(pdf_path: Path, out_dir: Path, dpi: int) -> list[Path]:
    """Run pdftoppm and normalize the output filenames to slide-NN.jpg."""
    # pdftoppm produces <prefix>-1.jpg, <prefix>-2.jpg, ...; padding depends on
    # the total page count. We post-process to a uniform 2-digit zero-padded
    # naming (`slide-01.jpg`, `slide-02.jpg`, ...) so the review template is
    # stable.
    raw_prefix = out_dir / "_raw_slide"
    cmd = ["pdftoppm", "-jpeg", "-r", str(dpi), str(pdf_path), str(raw_prefix)]
    subprocess.run(cmd, check=True, capture_output=True, text=True)

    raw_files = sorted(out_dir.glob("_raw_slide-*.jpg"))
    if not raw_files:
        raise RuntimeError(f"pdftoppm produced no JPEG at {raw_prefix}-*.jpg")

    renamed: list[Path] = []
    for i, raw in enumerate(raw_files, start=1):
        target = out_dir / f"slide-{i:02d}.jpg"
        if target.exists():
            target.unlink()
        raw.rename(target)
        renamed.append(target)
    return renamed


# ---------------------------------------------------------------------------
# Prompt + template generation
# ---------------------------------------------------------------------------
PROMPT_TEMPLATE = """# Visual Review Prompt — AOSIS Deck

You are reviewing a PowerPoint deck generated by the `aosis-deck-builder` skill.
Your job is to inspect each JPEG image (one per slide) and detect visual defects.

## What to look for

### Critical defects (block delivery)
- **Overflow**: text or shape extends beyond the slide edges (left < 0, right > 10", top < 0, bottom > 5.625").
- **Truncation**: text is visibly clipped (ends with "..." mid-word, or a word is missing its last characters — the canonical example is "éteinte" rendered as "éteint").
- **Empty slides**: a slide has no usable content (title placeholder only, body empty).

### Important defects (must fix before delivery)
- **Overlap**: two shapes overlap and the result is illegible.
- **Misalignment**: elements visibly not aligned (vertical or horizontal grids broken).
- **Palette breach**: a color that is NOT in the AOSIS palette appears. Valid colors: navy `#14163C`, orange `#F26622`, off-white `#FAFAF7`, gray `#4A4D6B`, gray-light `#E8E9F2`, white, navy-alt `#1E2261`, plus the matplotlib chart accents derived from these (`#7CB342`, `#F9B233`).
- **Font breach**: a font that is NOT Arial appears in body or title.
- **Descriptive title**: the slide title labels the slide ("Approche méthodologique", "Chiffres clés") instead of delivering a message ("Notre approche en 4 phases", "1,2 M€ pour reprendre 6h par cycle").

### Minor defects (improve if time)
- **Legibility**: text under 10pt or low contrast against background.
- **Density**: a slide with more than ~50 words of body text.
- **Visual rhythm**: bullet lists when a `cards` or `comparison` layout would land better.

## Output format

For each slide, fill the corresponding object in `review_report.template.json`.
Use the structure:

```json
{
  "slide": <int>,
  "image": "slide-<NN>.jpg",
  "defects": [
    {
      "severity": "critical|important|minor",
      "category": "overflow|alignment|legibility|palette|typography|title|empty",
      "description": "Free text. Be specific: which element, where on the slide."
    }
  ]
}
```

If a slide has no defect, leave `"defects": []`.

## Tips

- Always inspect at full image resolution (not thumbnails).
- Read every line of text fully — truncations are easy to miss.
- Compare slides to each other for typography and palette consistency.
- One pass is enough — list every defect once, do not re-flag the same issue across slides unless it really repeats.

When you're done, save the filled report as `review_report.json` (without the
`.template` suffix) in the same directory, then run:

```bash
python scripts/visual_review.py --summarize <output_dir>/review_report.json
```
"""


def write_prompt(out_dir: Path) -> Path:
    path = out_dir / "review_prompt.md"
    path.write_text(PROMPT_TEMPLATE, encoding="utf-8")
    return path


def write_report_template(out_dir: Path, deck_path: Path, n_slides: int) -> Path:
    """Write an empty report skeleton, one entry per slide."""
    payload = {
        "deck": str(deck_path),
        "reviewed_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "slides": [
            {"slide": i, "image": f"slide-{i:02d}.jpg", "defects": []}
            for i in range(1, n_slides + 1)
        ],
    }
    path = out_dir / "review_report.template.json"
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------
def prepare_review(pptx_path: Path, out_dir: Path, dpi: int, keep_pdf: bool) -> None:
    pptx_path = pptx_path.resolve()
    out_dir = out_dir.resolve()
    if not pptx_path.exists():
        raise SystemExit(f"Error: deck not found: {pptx_path}")
    out_dir.mkdir(parents=True, exist_ok=True)

    _check_system_dependencies()

    # Count slides up-front from the .pptx itself so the report template
    # matches even if conversion partially fails.
    n_slides = len(Presentation(str(pptx_path)).slides)

    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        pdf = _pptx_to_pdf(pptx_path, tmp)
        if keep_pdf:
            kept = out_dir / pdf.name
            shutil.copy(pdf, kept)
        jpegs = _pdf_to_jpegs(pdf, out_dir, dpi)

    prompt = write_prompt(out_dir)
    template = write_report_template(out_dir, pptx_path, n_slides)

    print(f"OK — {len(jpegs)} JPEG(s) at {dpi} dpi:")
    for j in jpegs:
        print(f"  {j}")
    print(f"Review prompt:   {prompt}")
    print(f"Report template: {template}")
    print(f"\nNext: have Claude read every JPEG, fill {template.name} as ")
    print(f"      {out_dir / 'review_report.json'}, then run:")
    print(f"      python {Path(__file__).name} --summarize {out_dir / 'review_report.json'}")


# ---------------------------------------------------------------------------
# Summarization
# ---------------------------------------------------------------------------
def summarize_report(report_path: "str | Path", out=sys.stdout) -> dict:
    """Read a filled review report and print a defect summary.

    Returns the parsed report dict for programmatic callers / tests.
    """
    report_path = Path(report_path)
    data = json.loads(report_path.read_text(encoding="utf-8"))
    deck = data.get("deck", "?")
    slides = data.get("slides", [])

    line = f"Visual review summary for {deck}"
    print(line, file=out)
    print("-" * len(line), file=out)

    total = Counter()
    for s in slides:
        idx = s.get("slide", "?")
        defects = s.get("defects", [])
        if not defects:
            print(f"Slide {idx}: 0 defects", file=out)
            continue
        c = Counter()
        for d in defects:
            sev = d.get("severity", "minor")
            cat = d.get("category", "unknown")
            c[(sev, cat)] += 1
            total[sev] += 1
        # Compose one line per slide listing severities and categories
        parts = []
        # Group by severity in the canonical order
        for sev in SEVERITIES:
            cats_at_sev = [cat for (s_, cat), n in c.items() if s_ == sev for _ in range(n)]
            if cats_at_sev:
                parts.append(f"{len(cats_at_sev)} {sev} ({', '.join(sorted(set(cats_at_sev)))})")
        print(f"Slide {idx}: {', '.join(parts)}", file=out)

    n_slides = len(slides)
    grand_total = sum(total.values())
    if grand_total == 0:
        print(f"\nTotal: 0 defects across {n_slides} slides.", file=out)
    else:
        line_parts = [f"{total[s]} {s}" for s in SEVERITIES if total[s]]
        print(f"\nTotal: {', '.join(line_parts)} across {n_slides} slides.", file=out)
    return data


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="visual_review.py",
        description="Convert a .pptx to JPEGs and generate a visual review prompt, "
                    "or summarize a filled review report.",
    )
    p.add_argument("pptx_path", nargs="?", help="Path to the .pptx to review")
    p.add_argument("output_dir", nargs="?",
                   help="Directory where JPEGs, prompt and report template will be written")
    p.add_argument("--dpi", type=int, default=150, help="JPEG resolution (default 150)")
    p.add_argument("--keep-pdf", action="store_true",
                   help="Keep the intermediate PDF (default: cleaned up)")
    p.add_argument("--summarize", metavar="REPORT",
                   help="Skip preparation and print a defects summary from REPORT.json")
    return p


def main(argv=None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.summarize:
        summarize_report(args.summarize)
        return 0

    if not (args.pptx_path and args.output_dir):
        parser.error("pptx_path and output_dir are required (or use --summarize REPORT)")

    prepare_review(
        pptx_path=Path(args.pptx_path),
        out_dir=Path(args.output_dir),
        dpi=args.dpi,
        keep_pdf=args.keep_pdf,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
